'use server'

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { supabaseAdmin } from '@/lib/supabase/admin'
import { canAdminManageOwn } from '@/lib/authz'

// Mirrors app/actions/collaborators.ts for recurring schedules. Sharing a
// schedule also shares its generated tasks (decision 2026-06-11): the cron
// generator grants new tasks, shareSchedule backfills existing ones, and
// removeScheduleCollaborator revokes them all again.

const CHUNK = 500

// ── helpers ────────────────────────────────────────────────────────────────────

async function requireScheduleOwner(
  supabase: Awaited<ReturnType<typeof createClient>>,
  userId: string,
  userEmail: string | null | undefined,
  userRole: string | null | undefined,
  scheduleId: string,
): Promise<{ error: string } | { title: string; createdBy: string }> {
  const { data: sched } = await supabase
    .from('task_schedules')
    .select('id, task_templates ( title, created_by )')
    .eq('id', scheduleId)
    .single()
  const template = sched?.task_templates as unknown as { title: string; created_by: string | null } | null
  if (!sched || !template) return { error: 'Lịch định kỳ không tồn tại' }
  if (!template.created_by) return { error: 'Lịch không có người tạo' }
  if (!canAdminManageOwn({ email: userEmail, role: userRole, createdBy: template.created_by, userId }))
    return { error: 'Chỉ admin tạo lịch hoặc super admin mới chia sẻ được' }
  return { title: template.title, createdBy: template.created_by }
}

async function scheduleTaskIds(scheduleId: string): Promise<string[]> {
  const ids: string[] = []
  let from = 0
  for (;;) {
    const { data, error } = await supabaseAdmin
      .from('tasks')
      .select('id')
      .eq('source_schedule_id', scheduleId)
      .range(from, from + CHUNK - 1)
    if (error) throw new Error(error.message)
    ids.push(...(data ?? []).map((t) => t.id))
    if (!data || data.length < CHUNK) break
    from += CHUNK
  }
  return ids
}

// ── shareSchedule ──────────────────────────────────────────────────────────────

export async function shareSchedule(
  scheduleId: string,
  adminId: string,
  permission: 'view' | 'editor',
) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  const { data: profile } = await supabase.from('users').select('role').eq('id', user.id).single()
  const check = await requireScheduleOwner(supabase, user.id, user.email, profile?.role, scheduleId)
  if ('error' in check) return check

  if (adminId === user.id) return { error: 'Không thể chia sẻ lịch với chính mình' }
  if (adminId === check.createdBy) return { error: 'Người tạo lịch đã có toàn quyền' }
  const { data: target } = await supabase.from('users').select('role').eq('id', adminId).single()
  if (!target) return { error: 'Người dùng không tồn tại' }
  if (target.role !== 'admin') return { error: 'Chỉ chia sẻ được với tài khoản admin' }

  // invited_by must equal the template owner so the owner always sees their
  // shares via tsc_select (invited_by = auth.uid()) — mirrors task sharing.
  const { error } = await supabase.from('task_schedule_collaborators').upsert(
    { schedule_id: scheduleId, admin_id: adminId, permission, invited_by: check.createdBy },
    { onConflict: 'schedule_id,admin_id' },
  )
  if (error) return { error: error.message }

  // Backfill: share every task already generated by this schedule. Overwrites
  // the permission on existing rows so the schedule-level choice wins.
  try {
    const taskIds = await scheduleTaskIds(scheduleId)
    for (let i = 0; i < taskIds.length; i += CHUNK) {
      const rows = taskIds.slice(i, i + CHUNK).map((taskId) => ({
        task_id: taskId, admin_id: adminId, permission, invited_by: check.createdBy,
      }))
      const { error: bfError } = await supabaseAdmin
        .from('task_collaborators')
        .upsert(rows, { onConflict: 'task_id,admin_id' })
      if (bfError) throw new Error(bfError.message)
    }
  } catch (err) {
    // Schedule share itself succeeded; surface the partial state honestly.
    const msg = err instanceof Error ? err.message : String(err)
    return { error: `Đã chia sẻ lịch nhưng gán quyền task đã tạo bị lỗi: ${msg}` }
  }

  await supabaseAdmin.from('notifications').insert({
    user_id: adminId,
    type:    'task_shared',
    task_id: null,
    title:   'Lịch định kỳ được chia sẻ với bạn',
    message: `"${check.title}" — quyền: ${permission === 'editor' ? 'Biên tập' : 'Xem'}`,
  })

  revalidatePath(`/tasks/schedules/${scheduleId}`)
  revalidatePath('/tasks/schedules')
  return { success: true }
}

// ── updateScheduleCollaboratorPermission ───────────────────────────────────────

export async function updateScheduleCollaboratorPermission(
  scheduleId: string,
  adminId: string,
  permission: 'view' | 'editor',
) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  const { data: profile } = await supabase.from('users').select('role').eq('id', user.id).single()
  const check = await requireScheduleOwner(supabase, user.id, user.email, profile?.role, scheduleId)
  if ('error' in check) return check

  const { error } = await supabase
    .from('task_schedule_collaborators')
    .update({ permission })
    .eq('schedule_id', scheduleId)
    .eq('admin_id', adminId)
  if (error) return { error: error.message }

  // Propagate to the generated tasks' collaborator rows.
  try {
    const taskIds = await scheduleTaskIds(scheduleId)
    for (let i = 0; i < taskIds.length; i += CHUNK) {
      const { error: upError } = await supabaseAdmin
        .from('task_collaborators')
        .update({ permission })
        .eq('admin_id', adminId)
        .in('task_id', taskIds.slice(i, i + CHUNK))
      if (upError) throw new Error(upError.message)
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    return { error: `Đã đổi quyền trên lịch nhưng đồng bộ task bị lỗi: ${msg}` }
  }

  revalidatePath(`/tasks/schedules/${scheduleId}`)
  return { success: true }
}

// ── removeScheduleCollaborator ─────────────────────────────────────────────────

export async function removeScheduleCollaborator(scheduleId: string, adminId: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  const { data: profile } = await supabase.from('users').select('role').eq('id', user.id).single()
  const check = await requireScheduleOwner(supabase, user.id, user.email, profile?.role, scheduleId)
  if ('error' in check) return check

  const { error } = await supabase
    .from('task_schedule_collaborators')
    .delete()
    .eq('schedule_id', scheduleId)
    .eq('admin_id', adminId)
  if (error) return { error: error.message }

  // Revoke access to generated tasks too (decision 2026-06-11). Note: this
  // also removes a per-task share of the same admin on this schedule's tasks.
  try {
    const taskIds = await scheduleTaskIds(scheduleId)
    for (let i = 0; i < taskIds.length; i += CHUNK) {
      const { error: delError } = await supabaseAdmin
        .from('task_collaborators')
        .delete()
        .eq('admin_id', adminId)
        .in('task_id', taskIds.slice(i, i + CHUNK))
      if (delError) throw new Error(delError.message)
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    return { error: `Đã gỡ khỏi lịch nhưng thu hồi quyền task bị lỗi: ${msg}` }
  }

  revalidatePath(`/tasks/schedules/${scheduleId}`)
  revalidatePath('/tasks/schedules')
  return { success: true }
}
